title: FIX ME
site-title: FIX ME
subtitle: >- # this means to ignore newlines until "baseurl:"
  FIX ME
description: >- # this means to ignore newlines until "baseurl:"
  SOMETHING HERE
baseurl: "" # add /blog
url: "FIX ME" # the base hostname & protocol for your site, e.g. http://example.com

lang: en

name: >-
  University of Illinois
about: >-
  Department of Mathematics <br>
  1409 W Green st, <br>
  Urbana Il, 61801

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']

# Build settings
markdown: kramdown
timezone: America/Chicago
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      type: "posts"
    values:
      layout: "posts"
      author: "Tyler Wang"
      permalink: /posts/:year/:month/:day/:title/
      comments: false
      footnotes: true
      tex: true
      theorem: true

sass:
  sass_dir: _sass
  style: compressed

menu-pages:
  - "Gallery"
  - "Package Info"
